In [1]:
import sys, os
sys.path.append(os.path.abspath("..//.."))

import pandas as pd
from database.database import *

In [2]:
bor = pd.read_csv(r"/Users/vijeetnigam/Library/CloudStorage/OneDrive-ALGO8AIPRIVATELIMITED/JK Tyre/Code/JK-CTP-Planning-Engine/vector_data/BORColorBandwiseReport__26-02-2026.csv")
bpr = pd.read_csv(r"/Users/vijeetnigam/Library/CloudStorage/OneDrive-ALGO8AIPRIVATELIMITED/JK Tyre/Code/JK-CTP-Planning-Engine/vector_data/BufferPenetrationReport__26-02-2026.csv")
bmr = pd.read_excel(r"/Users/vijeetnigam/Library/CloudStorage/OneDrive-ALGO8AIPRIVATELIMITED/JK Tyre/Code/JK-CTP-Planning-Engine/vector_data/Prod_OverAll_BMReport__26_02_2026.xlsx")

In [3]:
bmr.columns = bmr.iloc[0]
bmr = bmr.drop(index=0).reset_index(drop=True)

In [4]:
print(bor.columns)
# display(bor.head())

print(bpr.columns)
# display(bpr.head())

print(bmr.columns)
# display(bmr.head())

Index(['SKUCode', 'SKU Description', 'Location Code', 'Location Description',
       'SupplierCode', 'SupplierDesc', 'Norm ', 'Stock', 'Virtual Norm',
       'GIT/ Pending', 'Parent Leftover Stock', 'Requirement', 'Req TOB',
       'Req TOR', 'Req TOY', 'Req TOG', 'Req TOBlue', 'Dispatch Qty',
       'Dispatch TOB', 'Dispatch TOR', 'Dispatch TOY', 'Dispatch TOG',
       'Dispatch ToBlue', 'Dispatch Color', 'Adv Allocation',
       'Continuous Black', 'Continuous Black and Red', 'Latest Remark'],
      dtype='str')
Index(['Tags', 'SKUCode', 'Description', 'Location Code',
       'Location Description', 'Norm', 'Stock', 'On hand Inv. Pen',
       'On hand Inv. Color', 'GIT/ Pending', 'Pipeline Inv. Pen',
       'Pipeline Inv. Color', 'Normed Area (sq.ft)', 'Latest Remark',
       'SourceCode', 'SourceLocation', 'Location Type',
       'Stock Qty Reserved in OTM', 'Pending to Dispatch Qty in OTM',
       'Stocked Area (sq.ft)', 'Normed Area/ Actual Area (%)',
       'Stocked Area/ Actual Area (%)', 'Trigger', 'Actual Area (sq.ft)',
       'Tyre Type', 'Construction', 'Top SKU', 'Virtual Norm'],
      dtype='str')
Index(['BPP', 'Order Type', 'Order ID', 'Line Item', 'Item Code',
       'Item Description', 'Order Quantity', 'Due Date', 'CCRName ',
       'Release Date', 'Pending CCR Qty', 'Actual Release Date',
       'Total Delivered Qty', 'Plant Code', 'CCR Code', 'Pdn Full Kit',
       'Dispatch Full kit', 'PO Number', 'Route Logic', 'Allocated Qty EX10',
       'Allocated Qty EXPA', 'Allocated Qty EXPB', 'Allocated Qty EXPC',
       'Allocated Qty EXAA', 'Order Readiness Date at Billing Loc', 'SO Qty',
       'Billed Qty', 'Pending to Bill Qty', 'Customer Code',
       'Billing Location', 'SO Date', 'Customer Preferred Date',
       'Country Code', 'Segment', 'Line Item Dispatch Date',
       'Final Line item Ex-plant date'],
      dtype='object', name=0)

In [5]:
pcr_sku_list = get_data(f"sku_list_pcr")['SKU Code'].tolist()
tbr_sku_list = get_data(f"sku_list_tbr")['SKU Code'].tolist()

In [6]:
bor_pcr = bor[ bor["SKUCode"].isin(pcr_sku_list) & bor['Location Code'].str.startswith('1900')]
bor_tbr = bor[ bor["SKUCode"].isin(tbr_sku_list) & bor['Location Code'].str.startswith('1900')]

print(f"PCR: {bor_pcr['Requirement'].sum()}")
print(f"TBR: {bor_tbr['Requirement'].sum()}")

PCR: 164793
TBR: 42503

In [7]:
bpr_pcr = bpr[ bpr["SKUCode"].isin(pcr_sku_list) & bpr['Location Code'].str.startswith('1900')]
bpr_tbr = bpr[ bpr["SKUCode"].isin(tbr_sku_list) & bpr['Location Code'].str.startswith('1900')]

In [8]:
bmr_pcr = bmr[ bmr["Item Code"].isin(pcr_sku_list) & bmr['Plant Code'].str.startswith('1900')]
bmr_tbr = bmr[ bmr["Item Code"].isin(tbr_sku_list) & bmr['Plant Code'].str.startswith('1900')]

print(f"PCR: {bmr_pcr['Pending CCR Qty'].sum()}")
print(f"TBR: {bmr_tbr['Pending CCR Qty'].sum()}")

PCR: 1707
TBR: 1972

In [9]:
print("BOR PCR")
display(bor_pcr.head())

print("BOR TBR")
display(bor_tbr.head())

BOR PCR

,SKUCode,SKU Description,Location Code,Location Description,SupplierCode,SupplierDesc,Norm,Stock,Virtual Norm,GIT/ Pending,...,Dispatch TOB,Dispatch TOR,Dispatch TOY,Dispatch TOG,Dispatch ToBlue,Dispatch Color,Adv Allocation,Continuous Black,Continuous Black and Red,Latest Remark
1,1325223516103TURL0,235/65R16_UX ROYALE_103 T TL,1900_FG10,CTP_RE,1900,CTP,0,0,3,0,...,1,0,0,2,0,Black,0,-,-,NaN
8,1D25114012008QXPC0,145R12_ULTIMA XPC_8PR_Q_TT,1900_FG10,CTP_RE,1900,CTP,4232,0,4300,0,...,1507,0,1411,1410,0,Black,0,-,-,NaN
13,1325221317094VURL0,215/55R17_UX ROYALE_94V TL for KIA AY 17,1900_FG10,CTP_RE,1900,CTP,222,0,1034,0,...,377,37,387,233,0,Black,0,-,-,NaN
19,1325218316083HURL0,185/55R16_UX ROYALE_83 H TL,1900_FG10,CTP_RE,1900,CTP,715,0,715,0,...,418,0,238,238,0,Black,0,-,-,NaN
20,1325216514079TUTR0,165/65R14_UX TOURING_79T TL,1900_FG10,CTP_RE,1900,CTP,0,0,1,0,...,1,0,0,0,0,Black,0,-,-,NaN

BOR TBR

,SKUCode,SKU Description,Location Code,Location Description,SupplierCode,SupplierDesc,Norm,Stock,Virtual Norm,GIT/ Pending,...,Dispatch TOB,Dispatch TOR,Dispatch TOY,Dispatch TOG,Dispatch ToBlue,Dispatch Color,Adv Allocation,Continuous Black,Continuous Black and Red,Latest Remark
29,1121111020016KCXD0,11.00 R20_JDC XD_16PR_K_TT,1900_FG10,CTP_RE,1900,CTP,700,4,1302,0,...,177,534,377,233,0,Black,0,-,-,NaN
31,112222562C016MUXE0,255/70R22.5_JW_JUXe_16PR_140/137_M_TL,1900_FG10,CTP_RE,1900,CTP,228,29,1079,0,...,682,83,209,76,0,Black,0,-,-,NaN
36,1121111020016KDEP0,11.00R20_JDE++_16PR_K_TT,1900_FG10,CTP_RE,1900,CTP,1155,6,2449,0,...,444,746,878,385,0,Black,0,-,-,NaN
40,1122190020016KUH50,9.00R20_JUH5_16PR_K_TT,1900_FG10,CTP_RE,1900,CTP,326,4,995,0,...,339,153,391,108,0,Black,0,-,-,NaN
61,1121129A20152JCXD0,295/90R20_JDC XD_152/148_J_TT,1900_FG10,CTP_RE,1900,CTP,600,0,1156,0,...,200,270,494,200,0,Black,0,-,-,NaN

In [10]:
print("BPR PCR")
display(bpr_pcr.head())

print("BPR TBR")
display(bpr_tbr.head())

BPR PCR

,Tags,SKUCode,Description,Location Code,Location Description,Norm,Stock,On hand Inv. Pen,On hand Inv. Color,GIT/ Pending,...,Pending to Dispatch Qty in OTM,Stocked Area (sq.ft),Normed Area/ Actual Area (%),Stocked Area/ Actual Area (%),Trigger,Actual Area (sq.ft),Tyre Type,Construction,Top SKU,Virtual Norm
6427,NaN,1325215813079TUNE3,155/80R13 Ultima Neo 79T MSIL YL7 BSVI T,1900_OE10,CTP_OE,7000,0,100.0,Black,0,...,0,-,-,-,-,NaN,CAR,RADIAL,T,7000
6428,NaN,1325224716111SELS0,245/75 R 16_ELANZO SUPRA_111_S_TL,1900_OE10,CTP_OE,4000,0,100.0,Black,0,...,0,-,-,-,-,NaN,CAR,RADIAL,NaN,4000
6429,NaN,1D25215013008SXC10,155R13_ULTIMA XPC1_90/89S_TL_MSIL YG8,1900_OE10,CTP_OE,18000,0,100.0,Black,0,...,0,-,-,-,-,NaN,SCV,RADIAL,T,19178
6430,NaN,1D25215013008SXC1T,155R13C _ Ultima XPC1_8PR _TL_TML,1900_OE10,CTP_OE,4000,0,100.0,Black,0,...,0,-,-,-,-,NaN,SCV,RADIAL,T,4000
6431,NaN,1D25218014010RXPCT,185R14_ULTIMA XPC_10PR_R_TL,1900_OE10,CTP_OE,2000,0,100.0,Black,0,...,0,-,-,-,-,NaN,SCV,RADIAL,T,2000

BPR TBR

,Tags,SKUCode,Description,Location Code,Location Description,Norm,Stock,On hand Inv. Pen,On hand Inv. Color,GIT/ Pending,...,Pending to Dispatch Qty in OTM,Stocked Area (sq.ft),Normed Area/ Actual Area (%),Stocked Area/ Actual Area (%),Trigger,Actual Area (sq.ft),Tyre Type,Construction,Top SKU,Virtual Norm
6411,NaN,1122190020016KJH30,9.00R20_JUH3_16PR_K_TT,1900_ST10,CTP_ST,100,0,100.0,Black,0,...,0,-,-,-,-,NaN,TRUCK,RADIAL,NaN,100
6412,NaN,112222982C016MJUM0,295/80R22.5_JUM_16PR_154/149M_TL_EM,1900_ST10,CTP_ST,1500,0,100.0,Black,0,...,0,-,-,-,-,NaN,TRUCK,RADIAL,NaN,1500
6413,NaN,112222982C152MJXM0,295/80R22.5_JUM XM_16PR_152/148_M_TL_OEM,1900_ST10,CTP_ST,300,0,100.0,Black,0,...,0,-,-,-,-,NaN,TRUCK,RADIAL,NaN,300
6414,NaN,115222562C016MTH10,255/70R22.5_JTH1_DOT_16PR_M_TL,1900_ST10,CTP_ST,300,0,100.0,Black,0,...,0,-,-,-,-,NaN,TRUCK,RDL[DOT],NaN,300
6415,NaN,1121110020016KDEP0,10.00R20_JDE++_16PR_K_TT,1900_OE10,CTP_OE,150,0,100.0,Black,0,...,0,-,-,-,-,NaN,TRUCK,RADIAL,NaN,150

In [11]:
print("BMR PCR")
display(bmr_pcr.head())

print("BMR TBR")
display(bmr_tbr.head())

BMR PCR

,BPP,Order Type,Order ID,Line Item,Item Code,Item Description,Order Quantity,Due Date,CCRName,Release Date,...,Billed Qty,Pending to Bill Qty,Customer Code,Billing Location,SO Date,Customer Preferred Date,Country Code,Segment,Line Item Dispatch Date,Final Line item Ex-plant date
28,354,MTO,17375814,1325226517112HRXT0_1900,1325226517112HRXT0,265/65R17_RANGER X-A/T_112H TL,10,2025-12-11 00:00:00,Multi,2025-11-12 00:00:00,...,190,10,1301679,1900,2025-11-12,2025-12-03,PHI,PCR,2025-12-13,2025-12-11
29,354,MTO,17375814,1325226616111TBHT0_1900,1325226616111TBHT0,265/70R16 BLAZZE H/T 111T TL,1,2025-12-11 00:00:00,Multi,2025-11-12 00:00:00,...,49,1,1301679,1900,2025-11-12,2025-12-03,PHI,PCR,2025-12-13,2025-12-11
30,354,MTO,17375814,1325231015109RRXT0_1900,1325231015109RRXT0,31X10.50R15 LT RANGER X-A/T TL – 109 R,40,2025-12-11 00:00:00,Multi,2025-11-12 00:00:00,...,0,40,1301679,1900,2025-11-12,2025-12-03,PHI,PCR,2025-12-13,2025-12-11
31,354,MTO,17375814,1D25219Z14008SXC10_1900,1D25219Z14008SXC10,195R14_ULTIMA XPC1_8PR_S_TL,20,2025-12-11 00:00:00,Multi,2025-11-12 00:00:00,...,0,20,1301679,1900,2025-11-12,2025-12-03,PHI,PCR,2025-12-13,2025-12-11
32,337,MTO,17377003,1325218614088TTMX0_8009,1325218614088TTMX0,185/70 R14_TAXIMAX_88 T TL,0,2025-12-16 00:00:00,Multi,2025-11-17 00:00:00,...,0,200,1301679,8009,2025-11-13,2025-12-04,PHI,PCR,2025-12-18,2025-12-16

BMR TBR

,BPP,Order Type,Order ID,Line Item,Item Code,Item Description,Order Quantity,Due Date,CCRName,Release Date,...,Billed Qty,Pending to Bill Qty,Customer Code,Billing Location,SO Date,Customer Preferred Date,Country Code,Segment,Line Item Dispatch Date,Final Line item Ex-plant date
3,480,MTO,17343745,1153110020016KCDUC_8001,1153110020016KCDUC,10.00R20_CHALLENGER_CDU_DOT_16PR_K_TT,0,2025-11-03 00:00:00,Multi,2025-10-05 00:00:00,...,240,260,1302285,8001,2025-10-08,2025-10-29,BAN,TBR,2025-11-05,2025-11-03
5,454,MTO,17337122,1123110020016KJUC0_8001,1123110020016KJUC0,10.00R20_JUC_16PR_K_TT,0,2025-11-11 00:00:00,Multi,2025-10-13 00:00:00,...,430,20,1302233,8001,2025-09-29,2025-10-20,BAN,TBR,2025-11-13,2025-11-11
8,417,MTO,17365507,115223852C020KUH60_1900,115223852C020KUH60,385/65R22.5_JUH6_DOT_20PR_K_TL,112,2025-11-22 00:00:00,Multi,2025-10-24 00:00:00,...,388,112,1301684,1900,2025-10-31,2025-11-21,UNK,TBR,2025-11-24,2025-11-22
12,380,MTO,17365509,1122110020016KH3P0_8009,1122110020016KH3P0,10.00R20_JUH3+_16PR_K_TT,0,2025-12-03 00:00:00,Multi,2025-11-04 00:00:00,...,0,10,1301684,8009,2025-10-31,2025-11-21,UNK,TBR,2025-12-05,2025-12-03
14,380,MTO,17365509,1122111020016KUH50_8009,1122111020016KUH50,11.00R20_JUH5_150/147_K_TT,0,2025-12-03 00:00:00,Multi,2025-11-04 00:00:00,...,0,8,1301684,8009,2025-10-31,2025-11-21,UNK,TBR,2025-12-05,2025-12-03

In [12]:
bor_pcr.to_excel("bor_pcr.xlsx")
bor_tbr.to_excel("bor_tbr.xlsx")
bpr_pcr.to_excel("bpr_pcr.xlsx")
bpr_tbr.to_excel("bpr_tbr.xlsx")
bmr_pcr.to_excel("bmr_pcr.xlsx")
bmr_tbr.to_excel("bmr_tbr.xlsx")